### ISSUE TITLE
Potential glitch in Greeting CLI Lab

### ISSUE THREAD

**Issue by Green-stripes** [learn-co-curriculum/greeting-cli#14]
Hi, I've entered this code in my lib directory file but 2 of the 3 local tests are failing. When I run the code in irb it runs exactly like it says it should in the demo video. I think there may be an error with the lab? (Or am I being overconfident? :))

def greeting(name)
  puts "Hi! I'm HAL, what's your name?"
  name = gets.strip
  puts "Hello #{name}. It's nice to meet you."
end

**Comment by AnnJohn** [comment]
Hi @Green-stripes sorry for the delay with this. Since this is a question specific to your code, can you use the Ask a Question tool in Learn. It's the easiest way to get immediate help. Thanks!

**Comment by bondfan50** [comment]
Reopening this because the README needs further clarification.

I used the Ask a Question tool in Learn to figure out that I need to add the strip and chomp methods to *both* the executable file's 'gets' call AND the invocation in greeting.rb's 'puts' call.

This should not be necessary if the test was checking for the whole program to pass a check, but in this specific case the two tests are checking the exe and the rb files in a vacuum.  

Please consider adding a note to the README that warns the students about this redundancy.
