### ISSUE TITLE
gets.split

### ISSUE THREAD

**Issue by d-collins2** [learn-co-curriculum/greeting-cli#25]
gets.split doesn't allow for the white space to be removed.

**Comment by drakeltheryuujin** [comment]
Hi @d-collins2,

[Raising issues on GitHub](http://help.learn.co/improving-learn/contributing-to-lessons/raising-an-issue-with-a-lab-or-lesson) should be reserved for problems with the Learn.co curriculum. What exactly is the issue being raised? This lab asks for gets.strip to be used.  

This issue is being closed now as off-topic. If you still feel that this is an issue with the curriculum, please reopen the issue and provide more detail about why it's a curriculum issue.
